#!/usr/bin/perl -pib

# Update the home page with number of terms

# Denis Howe 1999-10-21 - 2011-05-17 13:03

# Not to be confused with /usr/bin/mkindex

BEGIN
{
    $numfile = 'contents/numterms';
    open F, $numfile or die "Can't read $numfile: $!";
    chomp ($numterms = <F>);
    close F;
    @s = stat 'Dictionary' or die "Can't stat Dictionary: $!";
	$bytes = $s[7];
    @d = localtime $s[9];
    $mdate = sprintf "%d-%02d-%02d %02d:%02d",
			  1900+$d[5], 1+$d[4], $d[3], $d[2], $d[1];
}

s|(numterms\D*)\d*|$1$numterms|;
s|(Last modified:) [-: \d]+|$1 $mdate|;

# Local variables:
# compile-command: "mkind home.html"
# End:
