#!/bin/sh

# 'doze
# c:/Bin/sink.cmd

# Mac
# u="$HOME/Applications/Unison.app/Contents/MacOS/Unison-gui" --> Symlink on PATH?
# sshargs for Unison is set in ~/Library/Application Support/Unison/foldoc.prf

export UNISON=~/Documents/Tech/Unison/home
u="unison -ui text foldoc"
$u -batch || $u
ssh -l denis -i ~/.ssh/personal/id_rsa foldoc make --directory=/var/www/foldoc.org
$u -batch || $u
