#!/bin/sh -x

# C:/Bin/sink.cmd passes this to bash

# Mac
# u="$HOME/Applications/Unison.app/Contents/MacOS/Unison-gui -ui text"
# --> Symlink on PATH?
# sshargs for Unison is set in ~/Library/Application Support/Unison/foldoc.prf

export UNISON=C:/Users/denis/Documents/Tech/Unison/home
u="unison foldoc"
$u -batch || $u
ssh -l denis foldoc make --directory=/var/www/foldoc.org
$u -batch || $u
